name: Run TypeScript File

on:
  pull_request:
    branches:
      - main

jobs:
  run-ts-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript file with ts-node for Homework1
        run: npx ts-node src/homework1/homework1.ts

      - name: Run TypeScript file with ts-node for Homework2
        run: npx ts-node src/homework2/homework2.ts

      - name: Run TypeScript file with ts-node for Homework2
        run: npx ts-node src/homework3/homework3.ts

      - name: Run TypeScript file with ts-node for Homework4
        run: npx ts-node src/homework4/homework4.ts

      - name: Run TypeScript file with ts-node for Homework6
        run: npx ts-node src/homework6/homework6.ts

      - name: Run TypeScript file with ts-node for Homework7
        run: npx ts-node src/homework7/homework7.ts
